### ISSUE TITLE
Incorrect google sitekey

### ISSUE THREAD

**Issue by FuckingToasters** [Matthew17-21/Captcha-Tools#10] opened 2022-10-19 21:14 UTC
Hi, when using anticaptcha i always get incorrect google sitekey issue even tho the sitekey is correct. i've looked in devtools network tab to confirm that it's correct and it cam out that it is. this is a url it requested to:

https://hcaptcha.com/checksiteconfig?v=1f7dc62&host=discord.com&sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34&sc=1&swa=1

As you can see, the sitekey is `f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34` which i use in my phone verifier. It worked fine for some time but now this issue happen and i don't know why -> key haven't changed.

Do you got any solution for that?

**Comment by Matthew17-21** [comment] 2022-10-20 11:47
Hi

Anyway to provide the code that you are using to test it?

Also, that error is returned by the site's api (either `ERROR_RECAPTCHA_INVALID_SITEKEY` or `ERROR_WRONG_GOOGLEKEY` depending on the site). Meaning that it's more of an error on their end, assuming everything is correct within your code.

While I haven't done any testing, I'd suggest making sure both the sitekey and the URL the captcha is on is 100% correct.

**Comment by FuckingToasters** [comment] 2022-10-20 12:45
> Hi
> 
> Anyway to provide the code that you are using to test it?
> 
> Also, that error is returned by the site's api (either `ERROR_RECAPTCHA_INVALID_SITEKEY` or `ERROR_WRONG_GOOGLEKEY` depending on the site). Meaning that it's more of an error on their end, assuming everything is correct within your code.
> 
> While I haven't done any testing, I'd suggest making sure both the sitekey and the URL the captcha is on is 100% correct.

Hi, yes here is the code
```py
import captchatools
import json
from plugins.configuration.load import config

class bypasscaptcha():
    def __init__(self):
        self.CAPTCHASERVICE, self.CAPTCHAKEY, self.SITEKEY, _, _, _, _, _, _, _ = config().loadconfig()

    def hcaptcha(self):
        solver = captchatools.captcha_harvesters(solving_site=self.CAPTCHASERVICE, api_key=self.CAPTCHAKEY, captcha_type="hcaptcha", sitekey=self.SITEKEY, captcha_url="https://discord.com/api/v9/users/@me/phone")
        self.CAPTCHATOKEN = solver.get_token()
        return self.CAPTCHATOKEN
 ```
 
 The contents of the variables used in the code are following:
 
 self.CAPTCHASERVICE = 2
 self.CAPTCHAKEY = "my scret key"
 self.SITEKEY = "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"
 
 Here a screenshot which show that the sitekey is indeed correct:
![1](https://user-images.githubusercontent.com/94435104/196952279-aec1ff99-7438-479e-a404-996abbf4e66a.png)

**Comment by Matthew17-21** [comment] 2022-10-20 20:45
Interesting. Ran it and it reproduced the expected error.

Looking further into it I can confirm, I see that AntiCaptcha is the one that is reporting it's an invalid key: `{"errorId":31,"errorCode":"ERROR_RECAPTCHA_INVALID_SITEKEY","errorDescription":"Recaptcha server reported that site key is invalid"}`.

I just triple checked their docs and nothing has changed. I opened a support ticket with them to report the false negative in hopes they fix it 😄. Aside from that, don't think I can do anything unfortunately.

Will keep you posted with their response.

**Comment by Matthew17-21** [comment] 2022-10-20 21:03
Interesting.

Using the `https://discordapp.com/api/v9/users/@me/phone` as the captcha_url along with the original sitekey throws no errors. Tried that?


This is the code that worked for me:
```py
import captchatools


CAP_KEY = "..."
SITEKEY = "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"
CAP_URL = "https://discordapp.com/api/v9/users/@me/phone"

solver = captchatools.captcha_harvesters(solving_site=2, api_key=CAP_KEY, captcha_type="hcaptcha", sitekey=SITEKEY, captcha_url=CAP_URL)
CAPTCHATOKEN = solver.get_token()
print(CAPTCHATOKEN)
```

**Comment by FuckingToasters** [comment] 2022-10-21 07:31
> Interesting.
> 
> Using the `https://discordapp.com/api/v9/users/@me/phone` as the captcha_url along with the original sitekey throws no errors. Tried that?
> 
> This is the code that worked for me:
> 
> ```python
> import captchatools
> 
> 
> CAP_KEY = "..."
> SITEKEY = "f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34"
> CAP_URL = "https://discordapp.com/api/v9/users/@me/phone"
> 
> solver = captchatools.captcha_harvesters(solving_site=2, api_key=CAP_KEY, captcha_type="hcaptcha", sitekey=SITEKEY, captcha_url=CAP_URL)
> CAPTCHATOKEN = solver.get_token()
> print(CAPTCHATOKEN)
> ```

Can confirm, using this url instead solved the issue however it seems like the solutions which these servies provide you with (capmonster & anticaptcha) are not great so discord won't consider sending a sms. I heard users from my tool saying that 2captcha works fine but i can't confirm this either as i just added $5 to 2captcha and so far discord haven't sent a sms too.

I've basically wasted some money now cause on anticaptcha i still got $30 left which i can't even use....

**Comment by Matthew17-21** [comment] 2022-10-21 12:43
Glad to hear using that url solved the issue. Going to close this issue. Will respond if and when I get an update from anticaptcha.

I'm also adding [nocaptchaai](https://nocaptchaai.com/) since another user says they have good rates. Maybe it'll work better for your case.

PS The good thing with anticaptcha is that they allow for [refunds](https://anti-captcha.com/clients/finance/requestfunds).

**Closed by Matthew17-21** 2022-10-21 12:43 UTC

**Comment by FuckingToasters** [comment] 2022-10-22 14:15
> Glad to hear using that url solved the issue. Going to close this issue. Will respond if and when I get an update from anticaptcha.
> 
> I'm also adding [nocaptchaai](https://nocaptchaai.com/) since another user says they have good rates. Maybe it'll work better for your case.
> 
> PS The good thing with anticaptcha is that they allow for [refunds](https://anti-captcha.com/clients/finance/requestfunds).

Hi, it seems to me that no single captcha solver (exscept 2captcha sometimes) provide a good quality captchatoken cause discird refuse to send a sms on these services for hours (2captcha sometimes work but around 1 time from 10 tries so not good too)

A new captcha implementation would be great, i've tried to add different AI Solvers by myself (not the https://nocaptchaai.com one) with no result i'm okay with. Hopefully your https://nocaptchaai.com  implementation will work better.

Thank you a lot for this Project :)
